services:
  - name: docverify-api
    type: web
    runtime: docker
    repo: https://github.com/rajsecrets/fastapiapp
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # Set this in the Render dashboard securely
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
